---
title: "Simulation and model analysis"
subtitle: "Non Linear Dynamics"
author: "Frederik Espersen Knudsen"
date: "2022-11-11"
output: pdf_document
---

# LAC Operon Model analysis
Based on Yildirim et al. 2004.  

See repository for more information.  

## Setup

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
```
  
\newpage  
# Scan of appropriate time step size
### Loading simulation results
Loading and structuring data:
```{r}
results_dir = "results/timestep_scan"
data <-
  tibble(filename = list.files(results_dir, pattern=".csv")) %>%
  mutate(model = map_chr(filename, ~ str_split(.x , " ") %>% pluck(1, 1)),
         timestep = map_chr(filename, ~ str_split(.x, " ") %>% pluck(1, 2) %>% str_split("=") %>% pluck(1, 2)),
         data = map(paste(results_dir, filename, sep="/"), read.csv),
         data = map(data, ~ .x %>% pivot_longer(-Time, names_to="Species", values_to="Concentration"))) %>%
  select(-filename)

data %>% glimpse()
data %>% pluck("data", 1) %>% head()
```

###  Visualizing results
```{r}
data %>%
  unnest(data) %>% 
  filter(Concentration > 0 & Concentration < 1000000000) %>%
  ggplot(aes(x=Time, y=Concentration, color=timestep, lty=model)) +
    geom_point(size=0.2) +
    facet_grid(Species~timestep, scales="free_y") +
    theme_bw()

data %>%
  unnest(data) %>% 
  filter(Concentration > 0 & Concentration < 1000000000) %>%
  filter(Time < 0.03) %>%
  ggplot(aes(x=Time, y=Concentration, color=timestep, lty=model)) +
    geom_point(size=0.2) +
    facet_grid(Species~timestep, scales="free_y") +
    xlab("Time [< 0.03]") +
    theme_bw()
```
